# Generated by Django 4.2.8 on 2023-12-20 14:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('contact_number', models.BigIntegerField()),
                ('account_created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('service_username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('contact_number', models.BigIntegerField()),
                ('account_created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('partnership_program', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('partner_id', models.AutoField(primary_key=True, serialize=False)),
                ('partnership_created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('partnership_program', models.CharField(max_length=100)),
                ('service_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.serviceprovider')),
            ],
        ),
    ]
